import { Routes } from '@angular/router';
import { Home } from './pages/home/home';
import { Impostazioni } from './pages/impostazioni/impostazioni';
import { SociList } from './features/soci/soci-list/soci-list';
import { SocioForm } from './features/soci/socio-form/socio-form';
import { DirettivoList } from './features/direttivo/direttivo-list/direttivo-list';
import { DirettivoForm } from './features/direttivo/direttivo-form/direttivo-form';
import { MusicistiList } from './features/musicisti/musicisti-list/musicisti-list';
import { MusicistaForm } from './features/musicisti/musicista-form/musicista-form';
import { MusicistaMusicale } from './features/musicisti/musicista-musicale/musicista-musicale';
import { PartitureList } from './features/partiture/partiture-list/partiture-list';
import { PartituraForm } from './features/partiture/partitura-form/partitura-form';
import { PartituraParti } from './features/parti/partitura-parti/partitura-parti';
import { RaccolteList } from './features/raccolte/raccolte-list/raccolte-list';
import { RaccoltaForm } from './features/raccolte/raccolta-form/raccolta-form';
import { RaccoltaDettaglio } from './features/raccolte/raccolta-dettaglio/raccolta-dettaglio';
import { AutoriList } from './features/autori/autori-list/autori-list';
import { AutoreForm } from './features/autori/autore-form/autore-form';
import { FamiglieList } from './features/famiglie/famiglie-list/famiglie-list';
import { FamigliaForm } from './features/famiglie/famiglia-form/famiglia-form';
import { StrumentiList } from './features/strumenti/strumenti-list/strumenti-list';
import { StrumentoForm } from './features/strumenti/strumento-form/strumento-form';
import { StrumentiFigliList } from './features/strumenti-figli/strumenti-figli-list/strumenti-figli-list';
import { StrumentoFiglioForm } from './features/strumenti-figli/strumento-figlio-form/strumento-figlio-form';
import { FormazioneSettings } from './features/formazione/formazione-settings/formazione-settings';
import { EventiList } from './features/calendario/eventi-list/eventi-list';
import { EventoForm } from './features/calendario/evento-form/evento-form';
import { EventoPresenze } from './features/calendario/evento-presenze/evento-presenze';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'impostazioni', component: Impostazioni },
  { path: 'soci', component: SociList },
  { path: 'soci/nuovo', component: SocioForm },
  { path: 'soci/:id', component: SocioForm },
  { path: 'direttivo', component: DirettivoList },
  { path: 'direttivo/nuovo', component: DirettivoForm },
  { path: 'direttivo/:id', component: DirettivoForm },
  { path: 'musicisti', component: MusicistiList },
  { path: 'musicisti/nuovo', component: MusicistaForm },
  { path: 'musicisti/:id/musicale', component: MusicistaMusicale },
  { path: 'musicisti/:id', component: MusicistaForm },
  { path: 'partiture', component: PartitureList },
  { path: 'partiture/nuovo', component: PartituraForm },
  { path: 'partiture/:id/parti', component: PartituraParti },
  { path: 'partiture/:id', component: PartituraForm },
  { path: 'raccolte', component: RaccolteList },
  { path: 'raccolte/nuovo', component: RaccoltaForm },
  { path: 'raccolte/:id/modifica', component: RaccoltaForm },
  { path: 'raccolte/:id', component: RaccoltaDettaglio },
  { path: 'autori', component: AutoriList },
  { path: 'autori/nuovo', component: AutoreForm },
  { path: 'autori/:id', component: AutoreForm },
  { path: 'famiglie', component: FamiglieList },
  { path: 'famiglie/nuovo', component: FamigliaForm },
  { path: 'famiglie/:id', component: FamigliaForm },
  { path: 'strumenti', component: StrumentiList },
  { path: 'strumenti/nuovo', component: StrumentoForm },
  { path: 'strumenti/:id', component: StrumentoForm },
  { path: 'strumenti-figli', component: StrumentiFigliList },
  { path: 'strumenti-figli/nuovo', component: StrumentoFiglioForm },
  { path: 'strumenti-figli/:id', component: StrumentoFiglioForm },
  { path: 'formazione', component: FormazioneSettings },
  { path: 'calendario', component: EventiList },
  { path: 'calendario/nuovo', component: EventoForm },
  { path: 'calendario/:id/presenze', component: EventoPresenze },
  { path: 'calendario/:id/modifica', component: EventoForm },
  { path: '**', redirectTo: '' }
];