import { Routes } from '@angular/router';
import { Home } from './pages/home/home';
import { BandistiList } from './features/bandisti/bandisti-list/bandisti-list';
import { BandistaForm } from './features/bandisti/bandista-form/bandista-form';
import { BandistaMusicale } from './features/bandisti/bandista-musicale/bandista-musicale';
import { PartitureList } from './features/partiture/partiture-list/partiture-list';
import { PartituraForm } from './features/partiture/partitura-form/partitura-form';
import { PartituraParti } from './features/parti/partitura-parti/partitura-parti';
import { LibrettiList } from './features/libretti/libretti-list/libretti-list';
import { LibrettoForm } from './features/libretti/libretto-form/libretto-form';
import { LibrettoDettaglio } from './features/libretti/libretto-dettaglio/libretto-dettaglio';
import { AutoriList } from './features/autori/autori-list/autori-list';
import { AutoreForm } from './features/autori/autore-form/autore-form';
import { FamiglieList } from './features/famiglie/famiglie-list/famiglie-list';
import { FamigliaForm } from './features/famiglie/famiglia-form/famiglia-form';
import { StrumentiList } from './features/strumenti/strumenti-list/strumenti-list';
import { StrumentoForm } from './features/strumenti/strumento-form/strumento-form';
import { StrumentiFigliList } from './features/strumenti-figli/strumenti-figli-list/strumenti-figli-list';
import { StrumentoFiglioForm } from './features/strumenti-figli/strumento-figlio-form/strumento-figlio-form';
import { BandaSettings } from './features/banda/banda-settings/banda-settings';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'bandisti', component: BandistiList },
  { path: 'bandisti/nuovo', component: BandistaForm },
  { path: 'bandisti/:id/musicale', component: BandistaMusicale },
  { path: 'bandisti/:id', component: BandistaForm },
  { path: 'partiture', component: PartitureList },
  { path: 'partiture/nuovo', component: PartituraForm },
  { path: 'partiture/:id/parti', component: PartituraParti },
  { path: 'partiture/:id', component: PartituraForm },
  { path: 'libretti', component: LibrettiList },
  { path: 'libretti/nuovo', component: LibrettoForm },
  { path: 'libretti/:id/modifica', component: LibrettoForm },
  { path: 'libretti/:id', component: LibrettoDettaglio },
  { path: 'autori', component: AutoriList },
  { path: 'autori/nuovo', component: AutoreForm },
  { path: 'autori/:id', component: AutoreForm },
  { path: 'famiglie', component: FamiglieList },
  { path: 'famiglie/nuovo', component: FamigliaForm },
  { path: 'famiglie/:id', component: FamigliaForm },
  { path: 'strumenti', component: StrumentiList },
  { path: 'strumenti/nuovo', component: StrumentoForm },
  { path: 'strumenti/:id', component: StrumentoForm },
  { path: 'strumenti-figli', component: StrumentiFigliList },
  { path: 'strumenti-figli/nuovo', component: StrumentoFiglioForm },
  { path: 'strumenti-figli/:id', component: StrumentoFiglioForm },
  { path: 'banda', component: BandaSettings },
  { path: '**', redirectTo: '' }
];